#!/usr/bin/env python

import I2C_LCD_driver
import time
import random

mylcd = I2C_LCD_driver.lcd()

#adding the spaces after each word is just a jank way of making sure the screen is clear every time run_display executes
#we at 91
firstLineData = ["hello               ",
        "good morning                    ",
        "fox n'                       ",
        "good morning                     ",
        "HEAD ON APPLY                    ",
        "whatcha doin                   ",
        "call your                  ",
        "call your                  ",
        "love you                  ",
        "try some                  ",
        "wonder if u                   ",
        "im a peepee                  ",
        "belle was                  ",
        "call ur                   ",
        "wonder how aunt                  ",
        "Even monkeys                  ",
        "Saru mo ki                  ",
        "Sumeba                  ",
        "Nana korobi,                  ",
        "Kappa mo                  ",
        "Juunin                  ",
        "Neko ni                  ",
        "Deru kugi wa                  ",
        "He wo hitte,                  ",
        "Ningen banji                  ",
        "May I take                  ",
        "SASAGEYO                  ",
        "ice cream                  ",
        "flip flop                  ",
        "handycap                  ",
        "bench press                  ",
        "omae wa                  ",
        "pandas                  ",
        "Go eat some                  ",
        "Want some pork                  ",
        "Tango                  ",
        "La                  ",
        "I like                  ",
        "Txt park                  ",
        "Screeny                 ",
        "Super                  ",
        "Try some                  ",
        "wake up wake up                  ",
        "the dew is on                  ",
        "wonder how                  ",
        "wonder how brycer                  ",
        "brush ur                   ",
        "did u                   ",
        "did u brush                  ",
        "bingo bayngo                  ",
        "How dusty                  ",
        "Read a                  ",
        "park is coding                  ",
        "get a haircut                  ",
        "today will                  ",
        "         (* ^ ω ^)         ",
        "        (＠＾◡＾)          ",
        "(((o(*°▽°*)o)))          ",
        "(◕‿◕)                  ",
        "ヽ(・∀・)ﾉ                  ",
        "(o･ω･o)                  ",
        "(^人^)                 ",
        "( ´ ω ` )                  ",
        "(´• ω •`)                  ",
        "╰(▔∀▔)╯                  ",
        "(✯◡✯)                  ",
        "(⌒‿⌒)                  ",
        "(*°▽°*)                  ",
        "(´｡• ᵕ •｡`)                  ",
        "ヽ(>∀<☆)ノ                  ",
        "＼(￣▽￣)／                  ",
        "(o˘◡˘o)                 ",
        "(╯✧▽✧)╯                  ",
        "    8‑D              ",
        "   ;‑]               ",
        "    :‑P              ",
        "     :‑O             ",
        "    <_<              ",
        "     =:o]             ",
        "    7:^]              ",
        "  <3 <3 <3                ",
        "   //0‑0\\               ",
        "   ⎛⎝(•ⱅ•)⎠⎞               ",
        "   >.<               ",
        "  V.v.V                ",
        "the early bird                  ",
        "pain is weakness                  ",
        "lets blow this                  ",
        "u need a                  ",
        "how bout u do                  ",
        "google 'kowloon                 ",
        "google 'north                  ",
        "where the fuck                  ",
        "r/evilbuildings                  ",
        "change ur sheets                  ",
        "6852 islands                  ",
        "P. Sherman 42                  ",
        
        ]

secondLineData = ["you damn fucker               ",
        "fella                    ",
        "falco                       ",
        "and good night                     ",
        "TO FOREHEAD                    ",
        "benny                   ",
        "mother                  ",
        "father                  ",
        "bwudda                  ",
        "oat milk                  ",
        "had nitemares                  ",
        "boy                  ",
        "a good pup                  ",
        "dang sister                  ",
        "Kim is doin'                  ",
        "fall from trees                  ",
        "kara ochiru                  ",
        "Miyako                  ",
        "ya oki                  ",
        "kawa nagare                  ",
        "tou iro                  ",
        "koban                  ",
        "utareru                  ",
        "shiri tsubome                  ",
        "saiou ga uma                  ",
        "Your Hat Sir?                  ",
        "SASAGEYOOO                  ",
        "soda                  ",
        "no feet                  ",
        "but eat meat                  ",
        "chest work                  ",
        "mou shinde iru                  ",
        "231                  ",
        "ramen 2day                  ",
        "liver paste?                  ",
        "Sucka!                  ",
        "Bambi!                  ",
        "Frozen Hotsauce                  ",
        "'persimmon man'                  ",
        "hungy 0_0                  ",
        "Salad?                  ",
        "boba tea 2day                  ",
        "the sun is up                  ",
        "the buttercup                  ",
        "nene is doin'                  ",
        "is doin'                  ",
        "teeth 2day?                  ",
        "floss 2day?                  ",
        "ur tongue 2day?                  ",
        "bongo                  ",
        "is that PC boi                 ",
        "fkn book                  ",
        "me at 8:43am                  ",
        "hippie                  ",
        "be lovely :D                 ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "gets the worm                  ",
        "leaving ur body                 ",
        "popsicle stand                 ",
        "break 2day bub                  ",
        "25 jumpin jacks                  ",
        "walled city'                  ",
        "sentinel island'                  ",
        "i am?                 ",
        "good sub                  ",
        "damn boi                  ",
        "in japan                  ",
        "Wallaby Way                  ",
        ]

"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",


### this is the original stuff to make the time and date display
# while True:
#     mylcd.lcd_display_string(time.strftime('%I:%M:%S %p'), 1)
#     mylcd.lcd_display_string(time.strftime('%a:%b:%d 20%y'), 2)

#function to make sure another function only runs once
def run_once(f):
    def wrapper(*args, **kwargs):
        if not wrapper.has_run:
            wrapper.has_run = True
            return f(*args, **kwargs)
    wrapper.has_run = False
    return wrapper



@run_once
def run_display():
        while True:
            listItemCorrelator = random.randint(0,90)
            #we use list(list)[number] to grab the list item w/ the same index as each other in both lists
            mylcd.lcd_display_string(list(firstLineData)[listItemCorrelator], 1)
            mylcd.lcd_display_string(list(secondLineData)[listItemCorrelator], 2)
            time.sleep(5)

#right now this only clears the display once.
#Find a way to clear the display after every time run_display executes
def clear_display():
    mylcd.lcd_display_string("", 1)
    mylcd.lcd_display_string("", 2)
                       
run_display()
clear_display()